#!/bin/bash

set -e
# set -x

basedir="`dirname $0`/.."
run_on="$1"
config="$2"

if [ -z "$run_on" -o -z "$config" -o ! -f "$config" ]; then
  echo "Usage: recipes/mkpi [instance|cluster|all] [config]"
  exit 1
else
  shift
  shift
fi

source "$config"

overcast run "$run_on" "$basedir/scripts/apt-get-dist-upgrade" "$@"

overcast run "$run_on" "$basedir/scripts/apt-get-install" --env "PACKAGES=\"htop zip collectd liboping0 $PACKAGES\"" "$@"

overcast run "$run_on" "$basedir/scripts/install-godaddy-c2-ca-root-cert-g2" "$@"

overcast run "$run_on" "$basedir/scripts/configure-collectd" "$@"

if [ "$LIBRATO" = "yes" ]; then
  overcast run "$run_on" "$basedir/scripts/configure-collectd-librato" --env "LIBRATO_USERNAME=\"$LIBRATO_USERNAME\" LIBRATO_PASSWORD=\"$LIBRATO_PASSWORD\"" "$@"
fi

if [ "$NOIP" = "yes" ]; then
  overcast run "$run_on" "$basedir/scripts/configure-noip-client" --env "NOIP_USERNAME=\"$NOIP_USERNAME\" NOIP_PASSWORD=\"$NOIP_PASSWORD\"" "$@"
fi

if [ "$WIFI" = "yes" ]; then
  overcast run "$run_on" "$basedir/scripts/configure-wifi" --env "WIFI_SSID=\"$WIFI_SSID\" WIFI_PASSWORD=\"$WIFI_PASSWORD\"" "$@"
fi

if [ "$PUBLIC_KEY" = "yes" ]; then
  overcast key push "$run_on" "$PUBLIC_KEY_FILE" --append "$@"
fi

if [ "$BLUEZ" = "yes" ]; then
  overcast run "$run_on" "$basedir/scripts/install-bluez-5" --env "BLUEZ_VERSION=\"$BLUEZ_VERSION\"" "$@"
fi

if [ "$LOCK_PI" = "yes" ]; then
  overcast run "$run_on" "sudo usermod --lock pi" "$@"
fi
