#!/bin/bash

set -e
# set -x

basedir="`dirname $0`/.."
run_on="$1"
ssh_key="$2"
wifi_ssid="$3"
wifi_password="$4"
noip_username="$5"
noip_password="$6"
librato_username="$7"
librato_password="$8"

if [ -z "$run_on" -o -z "$ssh_key" -o -z "$wifi_ssid" -o -z "$wifi_password" -o -z "$noip_username" -o -z "$noip_password" -o -z "$librato_username" -o -z "$librato_password" ]; then
  echo "Usage: recipes/mkrpi [instance|cluster|all] [ssh-key] [wifi-ssid] [wifi-password] [noip-username] [noip-password] [librato-username] [librato-password]"
  exit 1
else
  shift
  shift
  shift
  shift
  shift
  shift
  shift
  shift
fi

public_key_data=`overcast key get "$ssh_key" --public-data`
overcast run "$run_on" "$basedir/scripts/authorize-key" --env "PUBLIC_KEY=\"$public_key_data\"" "$@"

overcast run "$run_on" "$basedir/scripts/apt-get-dist-upgrade" "$@"

overcast run "$run_on" "$basedir/scripts/apt-get-install" --env "PACKAGES=\"htop zip collectd liboping0\"" "$@"

overcast run "$run_on" "$basedir/scripts/configure-wifi" --env "WIFI_SSID=\"$wifi_ssid\" WIFI_PASSWORD=\"$wifi_password\"" "$@"

overcast run "$run_on" "$basedir/scripts/configure-collectd" "$@"

overcast run "$run_on" "$basedir/scripts/configure-noip-client" --env "NOIP_USERNAME=\"$noip_username\" NOIP_PASSWORD=\"$noip_password\"" "$@"

overcast run "$run_on" "$basedir/scripts/configure-collectd-librato" --env "LIBRATO_USERNAME=\"$librato_username\" LIBRATO_PASSWORD=\"$librato_password\"" "$@"

overcast run "$run_on" "$basedir/scripts/install-godaddy-c2-ca-root-cert-g2" "$@"

overcast run "$run_on" "sudo usermod --lock pi" "$@"
