#!/bin/bash

set -e
# set -x

if [ -z "$PACKAGES" ]; then
  echo "Usage: scripts/apt-get-install --env \"PACKAGES=[package-name...]\""
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
/usr/bin/sudo /usr/bin/apt-get --quiet update
/usr/bin/sudo /usr/bin/apt-get --quiet --yes --no-install-recommends install $PACKAGES
