#!/bin/bash

set -e
# set -x

if [ -z "$PUBLIC_KEY" ]; then
  echo "Usage: scripts/authorize-key --env \"PUBLIC_KEY=[public-key-data]\""
  exit 1
fi

sshdir="$HOME/.ssh"
authorized_keys="$sshdir/authorized_keys"

pushd ~/

/bin/mkdir --parents "$sshdir"
/bin/echo "${PUBLIC_KEY}" >> "$authorized_keys"
/usr/bin/sort --unique "--output=$authorized_keys" "$authorized_keys"
/bin/chmod --recursive go-rwx "$sshdir"

popd
