#!/bin/bash

set -e
# set -x

pushd /tmp/

/bin/rm --force gdroot-g2.crt*
/usr/bin/wget --quiet 'https://certs.godaddy.com/repository/gdroot-g2.crt'

for cacerts in `/usr/bin/find /usr/lib/jvm -type f -name cacerts`; do
  /usr/bin/keytool -list -alias gdroot-g2 -keystore "$cacerts" -storepass changeit && continue
  
  [ -f "${cacerts}.DEFAULT" ] || /usr/bin/sudo /bin/cp "$cacerts" "${cacerts}.DEFAULT"
  /usr/bin/sudo /usr/bin/keytool -import -noprompt -file gdroot-g2.crt -alias gdroot-g2 -trustcacerts -keystore "$cacerts" -storepass changeit
done

popd
