#!/bin/bash

set -e
# set -x

export DEBIAN_FRONTEND=noninteractive

pushd /tmp/

# http://node-arm.herokuapp.com/
/usr/bin/wget --quiet 'http://node-arm.herokuapp.com/node_latest_armhf.deb'
/usr/bin/sudo /usr/bin/dpkg --install node_latest_armhf.deb

popd

/usr/bin/sudo /usr/local/bin/npm update --global
