#!/bin/bash

set -e
# set -x

if [ -z "$NOIP_USERNAME" -o -z "$NOIP_PASSWORD" ]; then
  echo "Usage: scripts/configure-noip-client --env \"NOIP_USERNAME=[username] NOIP_PASSWORD=[password]\""
  exit 1
fi

pushd /usr/local/src/

/usr/bin/sudo /usr/bin/curl --location --remote-name --silent 'http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz'
/usr/bin/sudo /bin/tar zxf noip-duc-linux.tar.gz

pushd noip-2.1.9*

/usr/bin/sudo /usr/bin/make

# /usr/bin/sudo /usr/bin/make install
/usr/bin/sudo /bin/cp noip2 /usr/local/bin/

echo '######################################################################################'
echo 'To configure the No-IP Dynamic Update Client, SSH to this instance and run:'
echo "/usr/bin/sudo /usr/local/bin/noip2 -C -F -U 30 -u '$NOIP_USERNAME' -p '$NOIP_PASSWORD'"
echo '/usr/bin/sudo /usr/local/bin/noip2'
echo '######################################################################################'

popd

popd

/usr/bin/sudo /usr/bin/tee /etc/cron.d/no-ip2 <<\EOF
# m h dom mon dow user command
@reboot root /usr/local/bin/noip2 -M
EOF
